### ISSUE TITLE
after installing 4.3.1 stable -> DB warning is away

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1856]
@mckillo: the DB warning persists

**Comment by mckillo** [comment]
I see it. In Joomla 5, multiple lines are being detected for the unregistra_until field.
![image](https://github.com/user-attachments/assets/2710506d-05c3-4515-baa5-f26b67db1090)
The field is correct, but a prior SQL file needs to be added before 4.3.1.sql, so Joomla doesn't detect any errors in the latest version, 4.3.1.sql.
Give me a few minutes, and I'll upload a commit.

**Comment by mckillo** [comment]
It doesn't work with other SQL files; I have to handle it directly in the install script. However, I need to step out now. I'll work on it this afternoon and have the new commit ready then. 
Stop to publish this zip file.

**Comment by mckillo** [comment]
As Joomla does not allow multiple type changes for database fields (via SQL files), the conversion of unregistra_until from int to datetime, along with the migration of its data, has been handled within the installation script of JEM 4.3.1.

I don't have permisions to upload commit with the fix (master to master). I create a new branch to mergue for this fix. Test it and it's is goog, add to final zip of 4.3.1

**Comment by jojo12** [comment]
I made a com_jem.zip and installed, the DB warning is fixed. can be committed into JEM 4.3.1 stable

**Comment by jojo12** [comment]
I would say, those who have installed it before a certain datetime, should download and install JEM 4.3.1 again!

**Comment by mckillo** [comment]
Version 4.3.1 was only available on GitHub from yesterday (night), while the website still shows version 4.3.0 and the update.xml file is also for 4.3.0. If anyone has installed version 4.3.1 previously ( I think that only us).

But if they reinstall, the update script doesn't run. The best solution is change the schema of JEM from 4.3.1 to 4.3.0, and reinstall.

**Comment by jojo12** [comment]
I think, this is not true: I reinstalled and the warning was away!

**Comment by mckillo** [comment]
Have you change the version in the schema table for Jem to 4.3.0?

**Comment by mckillo** [comment]
I'm mistake, un this case, you can change the JEM version(4.3.0) in the manifiest xml file.

**Comment by jojo12** [comment]
No I didn't
