### ISSUE TITLE
Show all events (both public and those with ACL active) but only to display the list of events.

### ISSUE THREAD

**Issue by mckillo** [jemproject/JEM-Project#1917]
Case from the Forum.

**Question:**
How can I display all events (both public and those with ACL restrictions) in any views where events are listed? Additionally, how can I download an iCal file that includes all events?

**Environment:**
- JEM 4.3.2
- Event 1: Access = Public
- Event 2: Access = Registered

**Current Behavior:**
In the event list view or calendar view, an iCal file download icon is displayed. However, if the user is not logged in, the iCal file only includes Event 1 (public). If the user logs in, the iCal file includes both Event 1 and Event 2.

**Comment by mckillo** [comment]
Possible solution (draft):

Adding a new parameter in the Global Settings to show all events in the list view. For example, this could include displaying a lock icon on the right side of the event title. This way, users can see the events and download the iCal file, but they won’t be able to access the event details unless they log in or have the necessary permissions.

The idea is to have an option in the JEM Global Settings that allows access to all events (both public and those with ACL active) but only to display the list of events. Currently, JEM (Joomla Event Manager) only has a single access setting, similar to Joomla articles.

![Image](https://github.com/user-attachments/assets/1513dd9b-335a-4a9f-bc1d-661df2fea162)

In the calendar view, the user can see events with ACL restrictions. However, if the user does not have permission to access the event, it is displayed with a closed lock icon. If the user attempts to access the event by clicking on the event title, JEM displays the following message:

![Image](https://github.com/user-attachments/assets/3116906d-4e05-45b8-9e17-4d76bc3dc724)

In the event list will be:

![Image](https://github.com/user-attachments/assets/7788dcdd-79df-4fb3-9ff8-1b72a7419536)

In this case, the user can still download the iCal file, which includes this event.

The admin could enable this functionality by adding a new parameter in the JEM Global Settings.

What is your opinion on this proposal?

**Comment by mckillo** [comment]
This new feature needs a branch https://github.com/jemproject/JEM-Project/tree/level-access-to-show-events.
I will upload the code for testing.

**Comment by mckillo** [comment]
![Image](https://github.com/user-attachments/assets/3254bbe7-1239-4e61-b17e-560bf301b21f)

**Comment by mckillo** [comment]
To testing in calendar view.
It will update the other views, next days.

**Comment by jojo12** [comment]
[Perhaps I don't understand enough!]
I am really not happy!
If what/when/where is public, then there is much too much information.
e.g. there is a meeting for a demonstration on a certain time on a certain place. This are too many public informations for people who want to disturb this. And an icon to inform, that this isn't public, doesn't help!
(I tried with: event is only for registered, Access Level is registered, then the event is visible for public but  with a Lock)

When I try with ACL public, then the event is hidden for public! This is much better!!!

**Comment by mckillo** [comment]
I have changed the definition of this new fied:

![Image](https://github.com/user-attachments/assets/b710e306-1f5f-4407-ad46-ddc4580b2f2d)

I think so; it's clearer and more understandable.
The public access level is always active by default to ensure compatibility with the current settings.
In the next commit, I fix some issues, add help text, and implement this field in the eventlist view.

**Comment by mckillo** [comment]
An in the second phase: 
I will also add an option to select which fields are included in the iCal file for locked events.
- UID
- CATEGORIES
- LINK
- LOCATION

**Comment by mckillo** [comment]
The new field is now named 'Show Locked Events'.
It is stored in `_jem_config` as `access_level_listview`.
This feature is active (show lock icon) in the following views: calendar, eventview, and others, for both responsive and legacy layouts.

**Comment by jojo12** [comment]
That means: events with visible lock can be exported with ical (only description and link not). Is this right?

**Comment by mckillo** [comment]
Yes, I think that it will be possible to filter this fields in the info of ical file.

**Comment by mckillo** [comment]
Yes, I think that it will be possible to filter this fields in the info of ical file.

"EDIT: By default, UID and LINK will not be included, except if in the setting is set to include link to the event (details).
I have doubts about LOCATION (venues) and CATEGORIES, because they have access, and that is the filter to include or nor.
What is your opinion?

**Comment by mckillo** [comment]
Venues have an access value in the `_jem_venues` table, but there is no code handling it :-(
I found an issue requesting support for access levels in venues (See #1122).
In next second phase, I wil try to dev it.

**Comment by mckillo** [comment]
![Image](https://github.com/user-attachments/assets/41427ce3-7e3c-4bd6-bbdd-8b7197088959)

If the category is Registered access, all its events aren't visible to the public user (as Joomla).

**Comment by mckillo** [comment]
![Image](https://github.com/user-attachments/assets/d0f49d89-451e-4f13-b15e-39323ddf4814)

Depending on the configuration and combination of the 3 new parameters, a lock icon will be displayed next to the category or event.

![Image](https://github.com/user-attachments/assets/8ac4f0b7-9204-44a6-b2ba-81696ad2547e)

**Comment by jojo12** [comment]
I tested with commit 91b5845 and got

in legacy:
Warning: Undefined property: stdClass::$user_has_access_category in site/components/com_jem/views/categories/tmpl/default.php on line 45

Warning: Undefined property: stdClass::$user_has_access_category in site/components/com_jem/views/categories/tmpl/default.php on line 36

in responsive

Warning: Undefined property: stdClass::$user_has_access_category in site/components/com_jem/views/categories/tmpl/responsive/default.php on line 43

Warning: Undefined property: stdClass::$user_has_access_category in site/components/com_jem/views/categories/tmpl/responsive/default.php on line 33

**Comment by mckillo** [comment]
Check you https://github.com/jemproject/JEM-Project/blob/support-access-level/site/models/categories.php file is updated (it's the same). In the line 436, you must have:

`$case_when_a  = ' CASE WHEN c.access IN (' . implode(',',$levels) . ') THEN 1 ELSE 0 END as user_has_access_category	,';`

I suppose that this file isn't updated.

**Comment by jojo12** [comment]
yes, you're right, sorry!

**Comment by jojo12** [comment]
But when I go to a category: I get in Legacy:
Warning: Undefined property: stdClass::$user_has_access in mysite.ch/components/com_jem/common/views/tmpl/default_events_table.php on line 120

**Comment by jojo12** [comment]
I found a new problem:
I can create new events in frontend AND backend. But when I try to open event detail views, it says I don't have the rights.

**Comment by mckillo** [comment]
I have reviewed all relevant views to refactor and update the access level variable. I believe that last two issues is resolved, but testing is still required.

**Comment by jojo12** [comment]
This problem persists!

> I found a new problem:
I can create new events in frontend AND backend. But when I try to open event detail views, it says I don't have the rights.
ALL rules for events, venues and categories are public. And all events, venues and categories are public

    Event not found!
    An error has occurred.
    For this I set the "releaseblocker"

Important to say:fI can open the older event, the problrm is only with the new created once!

**Comment by mckillo** [comment]
The bug related to events without a venue not being displayed has been resolved..
Add show venues registered when 'Show Locked Venue' is active for Registered.

**Comment by mckillo** [comment]
If 'Show Locked Venue' is set to 'Public,' the public event with a public venue is displayed.
If 'Show Locked Venue' is set to 'Public,' the public event with a registered venue is not displayed.
If 'Show Locked Venue' is set to 'Registered,' the public event with a registered venue is displayed, and the venue name is only shown with a lock icon.

**Comment by jojo12** [comment]
I am still not convinced, what's good on this visibility with lock image. 
But as long as there is a setting which lets the system as it is,  it's ok for me (Perhaps this can be good for others)

**Comment by mckillo** [comment]
To maintain JEM's current configuration, simply retain the default settings (all as 'public').

![Image](https://github.com/user-attachments/assets/104df1b8-4dcc-4c0c-a1df-01871e8ed9ae)

Do we need more time for additional testing, or can this feature be merged into the 4.3.3 branch now? For close this issue.

**Comment by jojo12** [comment]
I think, this can be closed. After all becauce there is a position which let the normal/earlier state.
So it's easier to test more.
I am not sure if you want the same comportment in the modules too?

**Comment by jojo12** [comment]
[I just posted the following proposal in #1122 too:]
It would perhaps be better to add an default text under the title of the eventslist [like an intro text]
that the visibility of events/venues/categories corresponds of users status.
User has to login for additional visibilities! Something like "To see all events relevant to you, you must first log in!"

The target is: if you have the relevant rights, the relevant events should be included in the ical-files.

**Comment by mckillo** [comment]
This has been merged, and I think it can be closed.
